/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AttendanceCreateEntryResponseBreaksInner } from './attendance-create-entry-response-breaks-inner';

/**
 * 
 * @export
 * @interface AttendanceCreateEntryResponse
 */
export interface AttendanceCreateEntryResponse {
    /**
     * The Kenjo _id of the new attendance entry.
     * @type {string}
     * @memberof AttendanceCreateEntryResponse
     */
    '_id'?: string;
    /**
     * The id of the employee assigned to the requested attendance entry.
     * @type {string}
     * @memberof AttendanceCreateEntryResponse
     */
    'userId'?: string;
    /**
     * The email of the employee assigned to the requested attendance entry.
     * @type {string}
     * @memberof AttendanceCreateEntryResponse
     */
    'email'?: string;
    /**
     * The external Id of the employee assigned to the requested attendance entry.
     * @type {string}
     * @memberof AttendanceCreateEntryResponse
     */
    'externalId'?: string;
    /**
     * The start date time of the created attendance entry
     * @type {string}
     * @memberof AttendanceCreateEntryResponse
     */
    'startTime'?: string;
    /**
     * The end date time of the created attendance entry.
     * @type {string}
     * @memberof AttendanceCreateEntryResponse
     */
    'endTime'?: string;
    /**
     * Array that contains the breaks in detail.
     * @type {Array<AttendanceCreateEntryResponseBreaksInner>}
     * @memberof AttendanceCreateEntryResponse
     */
    'breaks'?: Array<AttendanceCreateEntryResponseBreaksInner>;
    /**
     * DEPRECATED field, use the \'breaks\' field to specify the breaktime. The time in minutes to indicate a break of time. It cannot be greater than the total of minutes reported for the attendance entry.
     * @type {number}
     * @memberof AttendanceCreateEntryResponse
     */
    'breakTime'?: number;
    /**
     * Optional text to describe an attendance record (pair of startTime and endTime). The maximum number of characters is 150.
     * @type {string}
     * @memberof AttendanceCreateEntryResponse
     */
    'comment'?: string;
}

