/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AttendanceGetByIdResponseBreaksInner } from './attendance-get-by-id-response-breaks-inner';

/**
 * 
 * @export
 * @interface AttendanceGetByIdResponse
 */
export interface AttendanceGetByIdResponse {
    /**
     * The _id of the requested attendance entry.
     * @type {string}
     * @memberof AttendanceGetByIdResponse
     */
    '_id'?: string;
    /**
     * The id of the employee associated to the requested attendance entry.
     * @type {string}
     * @memberof AttendanceGetByIdResponse
     */
    'userId'?: string;
    /**
     * The email of the employee associated to the requested attendance entry.
     * @type {string}
     * @memberof AttendanceGetByIdResponse
     */
    'email'?: string;
    /**
     * The external Id of the employee associated to the requested attendance entry.
     * @type {string}
     * @memberof AttendanceGetByIdResponse
     */
    'externalId'?: string;
    /**
     * The start date time of the requested attendance entry.
     * @type {string}
     * @memberof AttendanceGetByIdResponse
     */
    'startTime'?: string;
    /**
     * The end date time of the requested attendance entry.
     * @type {string}
     * @memberof AttendanceGetByIdResponse
     */
    'endTime'?: string;
    /**
     * Array that contains the breaks in detail.
     * @type {Array<AttendanceGetByIdResponseBreaksInner>}
     * @memberof AttendanceGetByIdResponse
     */
    'breaks'?: Array<AttendanceGetByIdResponseBreaksInner>;
    /**
     * Number of minutes of break time. If there is no \'breaktime\' this field will not be in the response. This value is the sum of the total time of breaks.
     * @type {number}
     * @memberof AttendanceGetByIdResponse
     */
    'breakTime'?: number;
    /**
     * The Kenjo _id of the attendance category.
     * @type {string}
     * @memberof AttendanceGetByIdResponse
     */
    'attendanceCategoryId'?: string;
    /**
     * The Kenjo _id of the attendance sub category.
     * @type {string}
     * @memberof AttendanceGetByIdResponse
     */
    'attendanceSubCategoryId'?: string;
    /**
     * Optional text to describe an attendance record (pair of startTime and endTime). The maximum number of characters is 150.
     * @type {string}
     * @memberof AttendanceGetByIdResponse
     */
    'comment'?: string;
}

