/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AttendanceUpdateEntryResponse
 */
export interface AttendanceUpdateEntryResponse {
    /**
     * The _id of the requested attendance entry.
     * @type {string}
     * @memberof AttendanceUpdateEntryResponse
     */
    '_id'?: string;
    /**
     * The id of the employee associated to the requested attendance entry.
     * @type {string}
     * @memberof AttendanceUpdateEntryResponse
     */
    'userId'?: string;
    /**
     * The email of the employee associated to the requested attendance entry.
     * @type {string}
     * @memberof AttendanceUpdateEntryResponse
     */
    'email'?: string;
    /**
     * The external Id of the employee associated to the requested attendance entry.
     * @type {string}
     * @memberof AttendanceUpdateEntryResponse
     */
    'externalId'?: string;
    /**
     * The start date time of the requested attendance entry.
     * @type {string}
     * @memberof AttendanceUpdateEntryResponse
     */
    'startTime'?: string;
    /**
     * The end date time of the requested attendance entry.
     * @type {string}
     * @memberof AttendanceUpdateEntryResponse
     */
    'endTime'?: string;
    /**
     * DEPRECATED field, use the \'breaks\' field to specify the breaktime. The time in minutes to indicate a break of time. It cannot be greater than the total of minutes reported for the attendance entry.
     * @type {number}
     * @memberof AttendanceUpdateEntryResponse
     */
    'breakTime'?: number;
    /**
     * Optional text to describe an attendance record (pair of startTime and endTime). The maximum number of characters is 150.
     * @type {string}
     * @memberof AttendanceUpdateEntryResponse
     */
    'comment'?: string;
}

