/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AttendanceUpdateEntryRequestBreaksInner } from './attendance-update-entry-request-breaks-inner';

/**
 * 
 * @export
 * @interface AttendanceUpdateEntryRequest
 */
export interface AttendanceUpdateEntryRequest {
    /**
     * The new start time of the attendance entry to update. The valid format is *hh:mm:ss*
     * @type {string}
     * @memberof AttendanceUpdateEntryRequest
     */
    'startTime'?: string;
    /**
     * The new end time of the attendance entry to update. The valid format is *hh:mm:ss*
     * @type {string}
     * @memberof AttendanceUpdateEntryRequest
     */
    'endTime'?: string;
    /**
     * Array that contains the breaks in detail. Rules:<br> - A maximum of 10 breaks can be loaded via API.<br> - Breaks cannot be overlapped in the same day.<br> - \'start\' field is required.<br> - There is no way to update specifically a break.<br> - To remove \'breaks\', just send an empty array in the update, something like \"breaks\":[]
     * @type {Array<AttendanceUpdateEntryRequestBreaksInner>}
     * @memberof AttendanceUpdateEntryRequest
     */
    'breaks'?: Array<AttendanceUpdateEntryRequestBreaksInner>;
    /**
     * Optional text to describe an attendance record (pair of startTime and endTime). The maximum number of characters is 150.
     * @type {string}
     * @memberof AttendanceUpdateEntryRequest
     */
    'comment'?: string;
}

