/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AttendanceGetListResponseInnerBreaksInner } from './attendance-get-list-response-inner-breaks-inner';

/**
 * 
 * @export
 * @interface AttendanceGetListResponseInner
 */
export interface AttendanceGetListResponseInner {
    /**
     * The Kenjo _id of the returned attendance entry.
     * @type {string}
     * @memberof AttendanceGetListResponseInner
     */
    '_id'?: string;
    /**
     * The Kenjo _id of the employee assigned to the attendance entry.
     * @type {string}
     * @memberof AttendanceGetListResponseInner
     */
    'userId'?: string;
    /**
     * The Kenjo email of the employee assigned to the attendance entry.
     * @type {string}
     * @memberof AttendanceGetListResponseInner
     */
    'email'?: string;
    /**
     * The external id of the employee assigned to the attendance entry.
     * @type {string}
     * @memberof AttendanceGetListResponseInner
     */
    'externalId'?: string;
    /**
     * The start date time of the attendance entry.
     * @type {string}
     * @memberof AttendanceGetListResponseInner
     */
    'startTime'?: string;
    /**
     * The end date time of the attendance entry.
     * @type {string}
     * @memberof AttendanceGetListResponseInner
     */
    'endTime'?: string;
    /**
     * Array that contains the breaks in detail.
     * @type {Array<AttendanceGetListResponseInnerBreaksInner>}
     * @memberof AttendanceGetListResponseInner
     */
    'breaks'?: Array<AttendanceGetListResponseInnerBreaksInner>;
    /**
     * The break time of the attendance entry. If there is no \'breaktime\' this field will not be in the response. This value is the sum of the total time of breaks.
     * @type {string}
     * @memberof AttendanceGetListResponseInner
     */
    'breakTime'?: string;
    /**
     * The Kenjo _id of the attendance category.
     * @type {string}
     * @memberof AttendanceGetListResponseInner
     */
    'attendanceCategoryId'?: string;
    /**
     * The Kenjo _id of the attendance sub category.
     * @type {string}
     * @memberof AttendanceGetListResponseInner
     */
    'attendanceSubCategoryId'?: string;
    /**
     * Optional text to describe an attendance record (pair of startTime and endTime). The maximum number of characters is 150.
     * @type {string}
     * @memberof AttendanceGetListResponseInner
     */
    'comment'?: string;
}

