/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AttendanceCreateEntryRequestBreaksInner } from './attendance-create-entry-request-breaks-inner';

/**
 * 
 * @export
 * @interface AttendanceCreateEntryRequest
 */
export interface AttendanceCreateEntryRequest {
    /**
     * The Kenjo employee *_id*.
     * @type {string}
     * @memberof AttendanceCreateEntryRequest
     */
    'userId'?: string;
    /**
     * The Kenjo *email* for an employee.
     * @type {string}
     * @memberof AttendanceCreateEntryRequest
     */
    'email'?: string;
    /**
     * The *external id* for an employee for integrations.
     * @type {string}
     * @memberof AttendanceCreateEntryRequest
     */
    'externalId'?: string;
    /**
     * The date of the entry. The valid format is *YYYY-MM-DD*. Required field.
     * @type {string}
     * @memberof AttendanceCreateEntryRequest
     */
    'date': string;
    /**
     * The start time of the entry. The valid format is *hh:mm:ss*. Required field.
     * @type {string}
     * @memberof AttendanceCreateEntryRequest
     */
    'startTime': string;
    /**
     * The end time of the entry. It is not a required field but cannot be less or equal than the *startTime*. The valid format is *hh:mm:ss*
     * @type {string}
     * @memberof AttendanceCreateEntryRequest
     */
    'endTime'?: string;
    /**
     * Array that contains the breaks in detail. Rules:<br> - A maximum of 10 breaks can be loaded via API.<br> - Breaks cannot be overlapped in the same day.<br> - \'start\' field is required.
     * @type {Array<AttendanceCreateEntryRequestBreaksInner>}
     * @memberof AttendanceCreateEntryRequest
     */
    'breaks'?: Array<AttendanceCreateEntryRequestBreaksInner>;
    /**
     * Optional text to describe an attendance record (pair of startTime and endTime). The maximum number of characters is 150.
     * @type {string}
     * @memberof AttendanceCreateEntryRequest
     */
    'comment'?: string;
}

