/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CompaniesGetListResponseInner
 */
export interface CompaniesGetListResponseInner {
    /**
     * The Kenjo _id of the company.
     * @type {string}
     * @memberof CompaniesGetListResponseInner
     */
    '_id'?: string;
    /**
     * The name of the company.
     * @type {string}
     * @memberof CompaniesGetListResponseInner
     */
    'name'?: string;
    /**
     * The city of the company.
     * @type {string}
     * @memberof CompaniesGetListResponseInner
     */
    'city'?: string;
    /**
     * The country code of the company in ISO 3166-1 alpha-2.
     * @type {string}
     * @memberof CompaniesGetListResponseInner
     */
    'country'?: string;
}

