/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CompensationListAdditionalPaymentsResponseMetadata
 */
export interface CompensationListAdditionalPaymentsResponseMetadata {
    /**
     * The number of rows retrieved according the pagination filters (limit + offset).
     * @type {number}
     * @memberof CompensationListAdditionalPaymentsResponseMetadata
     */
    'count'?: number;
    /**
     * The number of pages to skip. Determines the page number when pagination is being used.
     * @type {number}
     * @memberof CompensationListAdditionalPaymentsResponseMetadata
     */
    'offset'?: number;
    /**
     * The maximum number of rows to retrieve. Determines the size of the page when pagination is being used.
     * @type {number}
     * @memberof CompensationListAdditionalPaymentsResponseMetadata
     */
    'limit'?: number;
    /**
     * The total number of rows existing for the provided filters.
     * @type {number}
     * @memberof CompensationListAdditionalPaymentsResponseMetadata
     */
    'total'?: number;
}

