/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CompensationGetSalariesListResponseDataInner
 */
export interface CompensationGetSalariesListResponseDataInner {
    /**
     * The Kenjo _id of the returned salary.
     * @type {string}
     * @memberof CompensationGetSalariesListResponseDataInner
     */
    '_id'?: string;
    /**
     * The employee id associated to the salary.
     * @type {string}
     * @memberof CompensationGetSalariesListResponseDataInner
     */
    '_userId'?: string;
    /**
     * The company id associated to the salary.
     * @type {string}
     * @memberof CompensationGetSalariesListResponseDataInner
     */
    '_companyId'?: string;
    /**
     * The start date (effective date) of the salary in format YYYY-MM-DDThh:mm:ss.
     * @type {string}
     * @memberof CompensationGetSalariesListResponseDataInner
     */
    'startDate'?: string;
    /**
     * The end date of the salary in format YYYY-MM-DDThh:mm:ss.
     * @type {string}
     * @memberof CompensationGetSalariesListResponseDataInner
     */
    'endDate'?: string;
    /**
     * The the amount of money associated to the salary.
     * @type {number}
     * @memberof CompensationGetSalariesListResponseDataInner
     */
    'amount'?: number;
    /**
     * The salary payment period.
     * @type {string}
     * @memberof CompensationGetSalariesListResponseDataInner
     */
    'paymentPeriod'?: string;
    /**
     * This currency in ISO 4217.
     * @type {number}
     * @memberof CompensationGetSalariesListResponseDataInner
     */
    'currency'?: number;
}

