/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CompensationListAdditionalPaymentsResponseDataInner
 */
export interface CompensationListAdditionalPaymentsResponseDataInner {
    /**
     * The Kenjo _id of the returned additional payment.
     * @type {string}
     * @memberof CompensationListAdditionalPaymentsResponseDataInner
     */
    '_id'?: string;
    /**
     * The employee id associated to the additional payment.
     * @type {string}
     * @memberof CompensationListAdditionalPaymentsResponseDataInner
     */
    '_userId'?: string;
    /**
     * The company id associated to the additional payment.
     * @type {string}
     * @memberof CompensationListAdditionalPaymentsResponseDataInner
     */
    '_companyId'?: string;
    /**
     * The effective date of the additional payment in format YYYY-MM-DDThh:mm:ss.
     * @type {string}
     * @memberof CompensationListAdditionalPaymentsResponseDataInner
     */
    'effectiveDate'?: string;
    /**
     * The id of the addional payment type in format YYYY-MM-DDThh:mm:ss.
     * @type {string}
     * @memberof CompensationListAdditionalPaymentsResponseDataInner
     */
    'additionalPaymentTypeId'?: string;
    /**
     * The the amount of money associated to the additional payment.
     * @type {number}
     * @memberof CompensationListAdditionalPaymentsResponseDataInner
     */
    'amount'?: number;
    /**
     * This currency in ISO 4217.
     * @type {number}
     * @memberof CompensationListAdditionalPaymentsResponseDataInner
     */
    'currency'?: number;
}

