/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeesGetListResponseDataInner
 */
export interface EmployeesGetListResponseDataInner {
    /**
     * The Kenjo employee _id.
     * @type {string}
     * @memberof EmployeesGetListResponseDataInner
     */
    '_id'?: string;
    /**
     * The employee email in Kenjo.
     * @type {string}
     * @memberof EmployeesGetListResponseDataInner
     */
    'email'?: string;
    /**
     * Indicates the active status of the Kenjo employee.
     * @type {string}
     * @memberof EmployeesGetListResponseDataInner
     */
    'isActive'?: string;
    /**
     * The external id for this employee.
     * @type {string}
     * @memberof EmployeesGetListResponseDataInner
     */
    'externalId'?: string;
    /**
     * The employee language. The available values are \'en\' (english), \'es\' (spanish) or \'de\' (german).
     * @type {string}
     * @memberof EmployeesGetListResponseDataInner
     */
    'language'?: string;
}

