/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeesGetAccountsResponseDataInner
 */
export interface EmployeesGetAccountsResponseDataInner {
    /**
     * The Kenjo _id of the returned attendance entry.
     * @type {string}
     * @memberof EmployeesGetAccountsResponseDataInner
     */
    '_id'?: string;
    /**
     * The Kenjo email of the employee.
     * @type {string}
     * @memberof EmployeesGetAccountsResponseDataInner
     */
    'email'?: string;
    /**
     * The external id of the employee.
     * @type {string}
     * @memberof EmployeesGetAccountsResponseDataInner
     */
    'externalId'?: string;
    /**
     * The employee language.
     * @type {string}
     * @memberof EmployeesGetAccountsResponseDataInner
     */
    'language'?: EmployeesGetAccountsResponseDataInnerLanguageEnum;
    /**
     * The employee activation status.
     * @type {boolean}
     * @memberof EmployeesGetAccountsResponseDataInner
     */
    'isActive'?: boolean;
}

type EmployeesGetAccountsResponseDataInnerLanguageEnum = 'en' | 'de' | 'es'


