/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeesUpdateFinancialsResponse
 */
export interface EmployeesUpdateFinancialsResponse {
    /**
     * The employee Kenjo *_id*.
     * @type {string}
     * @memberof EmployeesUpdateFinancialsResponse
     */
    '_id'?: string;
    /**
     * The accounts holder\'s name.
     * @type {string}
     * @memberof EmployeesUpdateFinancialsResponse
     */
    'accountHolderName'?: string;
    /**
     * The bank name.
     * @type {string}
     * @memberof EmployeesUpdateFinancialsResponse
     */
    'bankName'?: string;
    /**
     * The account number.
     * @type {string}
     * @memberof EmployeesUpdateFinancialsResponse
     */
    'accountNumber'?: string;
    /**
     * The IBAN.
     * @type {string}
     * @memberof EmployeesUpdateFinancialsResponse
     */
    'iban'?: string;
    /**
     * The SWIFT code.
     * @type {string}
     * @memberof EmployeesUpdateFinancialsResponse
     */
    'swiftCode'?: string;
    /**
     * The national id document.
     * @type {string}
     * @memberof EmployeesUpdateFinancialsResponse
     */
    'nationalId'?: string;
    /**
     * The passport number.
     * @type {string}
     * @memberof EmployeesUpdateFinancialsResponse
     */
    'passport'?: string;
    /**
     * The national insurance number
     * @type {string}
     * @memberof EmployeesUpdateFinancialsResponse
     */
    'nationalInsuranceNumber'?: string;
    /**
     * The tax number.
     * @type {string}
     * @memberof EmployeesUpdateFinancialsResponse
     */
    'taxCode'?: string;
    /**
     * The tax identification number.
     * @type {string}
     * @memberof EmployeesUpdateFinancialsResponse
     */
    'taxIdentificationNumber'?: string;
}

