/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeesUpdateAddressResponse
 */
export interface EmployeesUpdateAddressResponse {
    /**
     * The employee Kenjo *_id*.
     * @type {string}
     * @memberof EmployeesUpdateAddressResponse
     */
    '_id'?: string;
    /**
     * The name of the street.
     * @type {string}
     * @memberof EmployeesUpdateAddressResponse
     */
    'street'?: string;
    /**
     * The postal code.
     * @type {string}
     * @memberof EmployeesUpdateAddressResponse
     */
    'postalCode'?: string;
    /**
     * The city.
     * @type {string}
     * @memberof EmployeesUpdateAddressResponse
     */
    'city'?: string;
    /**
     * The country code in ISO 3166-1 alpha-2.
     * @type {string}
     * @memberof EmployeesUpdateAddressResponse
     */
    'country'?: string;
}

