/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeesUpdateWorkScheduleRequest
 */
export interface EmployeesUpdateWorkScheduleRequest {
    /**
     * Allow to indicate if mondays are working days for the employee.
     * @type {boolean}
     * @memberof EmployeesUpdateWorkScheduleRequest
     */
    'mondayWorkingDay'?: boolean;
    /**
     * Allow to indicate if tuesdays are working days for the employee.
     * @type {boolean}
     * @memberof EmployeesUpdateWorkScheduleRequest
     */
    'tuesdayWorkingDay'?: boolean;
    /**
     * Allow to indicate if wednesdays are working days for the employee.
     * @type {boolean}
     * @memberof EmployeesUpdateWorkScheduleRequest
     */
    'wednesdayWorkingDay'?: boolean;
    /**
     * Allow to indicate if thursdays are working days for the employee.
     * @type {boolean}
     * @memberof EmployeesUpdateWorkScheduleRequest
     */
    'thursdayWorkingDay'?: boolean;
    /**
     * Allow to indicate if fridays are working days for the employee.
     * @type {boolean}
     * @memberof EmployeesUpdateWorkScheduleRequest
     */
    'fridayWorkingDay'?: boolean;
    /**
     * Allow to indicate if saturdays are working days for the employee.
     * @type {boolean}
     * @memberof EmployeesUpdateWorkScheduleRequest
     */
    'saturdayWorkingDay'?: boolean;
    /**
     * Allow to indicate if sundays are working days for the employee.
     * @type {boolean}
     * @memberof EmployeesUpdateWorkScheduleRequest
     */
    'sundayWorkingDay'?: boolean;
}

