/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeesGetEmployeeInformationResponseAccount
 */
export interface EmployeesGetEmployeeInformationResponseAccount {
    /**
     * The employee Kenjo *_id*.
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseAccount
     */
    '_id'?: string;
    /**
     * The employee email in Kenjo. This is an unique identifier and required.
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseAccount
     */
    'email'?: string;
    /**
     * The employee external id for integration proposals.
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseAccount
     */
    'externalId'?: string;
    /**
     * The employee activation status.
     * @type {boolean}
     * @memberof EmployeesGetEmployeeInformationResponseAccount
     */
    'isActive'?: boolean;
    /**
     * The employee language. The available values are \'en\' (english), \'es\' (spanish) or \'de\' (german).
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseAccount
     */
    'language'?: string;
}

