/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeesGetEmployeeInformationResponseHome
 */
export interface EmployeesGetEmployeeInformationResponseHome {
    /**
     * The marital status. Only is valid one of the following values \"Divorced\", \"Domestic Partnership\", \"Married\", \"Separated\", \"Single\", \"Widowed\".
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseHome
     */
    'maritalStatus'?: string;
    /**
     * The first name of the employee\'s spouse.
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseHome
     */
    'spouseFirstName'?: string;
    /**
     * The last name of the employee\'s spouse.
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseHome
     */
    'spouseLastName'?: string;
    /**
     * The birth date of the employee\'s spouse. Format YYYY-MM-DDThh:mm:ss.000Z.
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseHome
     */
    'spouseBirthdate'?: string;
    /**
     * The employee\'s spouse gender. Only is valid one of the following values \'Male\' (male), \'Female\' (female) or \'Other\' (other).
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseHome
     */
    'spouseGender'?: string;
    /**
     * The employee personal email.
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseHome
     */
    'personalEmail'?: string;
    /**
     * The employee personal phone.
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseHome
     */
    'personalPhone'?: string;
    /**
     * The employee personal phone
     * @type {string}
     * @memberof EmployeesGetEmployeeInformationResponseHome
     */
    'personalMobile'?: string;
}

