/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeesListFinancialsResponseDataInner
 */
export interface EmployeesListFinancialsResponseDataInner {
    /**
     * The _id of the Kenjo employee.
     * @type {string}
     * @memberof EmployeesListFinancialsResponseDataInner
     */
    '_id'?: string;
    /**
     * The accounts holder\'s name.
     * @type {string}
     * @memberof EmployeesListFinancialsResponseDataInner
     */
    'accountHolderName'?: string;
    /**
     * The bank name.
     * @type {string}
     * @memberof EmployeesListFinancialsResponseDataInner
     */
    'bankName'?: string;
    /**
     * The account number.
     * @type {string}
     * @memberof EmployeesListFinancialsResponseDataInner
     */
    'accountNumber'?: string;
    /**
     * The IBAN.
     * @type {string}
     * @memberof EmployeesListFinancialsResponseDataInner
     */
    'iban'?: string;
    /**
     * The SWIFT code.
     * @type {string}
     * @memberof EmployeesListFinancialsResponseDataInner
     */
    'swiftCode'?: string;
    /**
     * The national id document.
     * @type {string}
     * @memberof EmployeesListFinancialsResponseDataInner
     */
    'nationalId'?: string;
    /**
     * The passport number.
     * @type {string}
     * @memberof EmployeesListFinancialsResponseDataInner
     */
    'passport'?: string;
    /**
     * The national insurance number.
     * @type {string}
     * @memberof EmployeesListFinancialsResponseDataInner
     */
    'nationalInsuranceNumber'?: string;
    /**
     * The tax number.
     * @type {string}
     * @memberof EmployeesListFinancialsResponseDataInner
     */
    'taxCode'?: string;
    /**
     * The tax identification number.
     * @type {string}
     * @memberof EmployeesListFinancialsResponseDataInner
     */
    'taxIdentificationNumber'?: string;
}

