/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OfficesGetListResponseInner
 */
export interface OfficesGetListResponseInner {
    /**
     * The Kenjo _id of the office.
     * @type {string}
     * @memberof OfficesGetListResponseInner
     */
    '_id'?: string;
    /**
     * The name of the office.
     * @type {string}
     * @memberof OfficesGetListResponseInner
     */
    'name'?: string;
    /**
     * The Kenjo id of the company.
     * @type {string}
     * @memberof OfficesGetListResponseInner
     */
    'companyId'?: string;
    /**
     * The Kenjo id of the calendar.
     * @type {string}
     * @memberof OfficesGetListResponseInner
     */
    'calendarId'?: string;
    /**
     * The street of the office.
     * @type {string}
     * @memberof OfficesGetListResponseInner
     */
    'street'?: string;
    /**
     * The postal code of the office.
     * @type {string}
     * @memberof OfficesGetListResponseInner
     */
    'postalCode'?: string;
    /**
     * The city of the office.
     * @type {string}
     * @memberof OfficesGetListResponseInner
     */
    'city'?: string;
    /**
     * The country of the office in ISO code.
     * @type {string}
     * @memberof OfficesGetListResponseInner
     */
    'country'?: string;
}

