/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OfficesGetByIdResponse
 */
export interface OfficesGetByIdResponse {
    /**
     * The Kenjo _id of the office.
     * @type {string}
     * @memberof OfficesGetByIdResponse
     */
    '_id'?: string;
    /**
     * The name of the office.
     * @type {string}
     * @memberof OfficesGetByIdResponse
     */
    'name'?: string;
    /**
     * The Kenjo id of the company.
     * @type {string}
     * @memberof OfficesGetByIdResponse
     */
    'companyId'?: string;
    /**
     * The Kenjo id of the calendar.
     * @type {string}
     * @memberof OfficesGetByIdResponse
     */
    'calendarId'?: string;
    /**
     * The street of the office.
     * @type {string}
     * @memberof OfficesGetByIdResponse
     */
    'street'?: string;
    /**
     * The postal code of the office.
     * @type {string}
     * @memberof OfficesGetByIdResponse
     */
    'postalCode'?: string;
    /**
     * The city of the office.
     * @type {string}
     * @memberof OfficesGetByIdResponse
     */
    'city'?: string;
    /**
     * The country of the office in ISO code.
     * @type {string}
     * @memberof OfficesGetByIdResponse
     */
    'country'?: string;
}

