/*
Kenjo API

Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserAccountsListEmployeesResponseInner
 */
export interface UserAccountsListEmployeesResponseInner {
    /**
     * The Kenjo employee _id.
     * @type {string}
     * @memberof UserAccountsListEmployeesResponseInner
     */
    '_id'?: string;
    /**
     * The employee email in Kenjo.
     * @type {string}
     * @memberof UserAccountsListEmployeesResponseInner
     */
    'email'?: string;
    /**
     * Indicates the active status of the Kenjo employee.
     * @type {string}
     * @memberof UserAccountsListEmployeesResponseInner
     */
    'isActive'?: string;
    /**
     * The first name of the Kenjo employee.
     * @type {string}
     * @memberof UserAccountsListEmployeesResponseInner
     */
    'firstName'?: string;
    /**
     * The last name of the Kenjo employee.
     * @type {string}
     * @memberof UserAccountsListEmployeesResponseInner
     */
    'lastName'?: string;
    /**
     * The complete name of the Kenjo employee.
     * @type {string}
     * @memberof UserAccountsListEmployeesResponseInner
     */
    'displayName'?: string;
    /**
     * The Kenjo Id of the company for this employee.
     * @type {string}
     * @memberof UserAccountsListEmployeesResponseInner
     */
    'companyId'?: string;
    /**
     * The Kenjo Id of the office for this employee.
     * @type {string}
     * @memberof UserAccountsListEmployeesResponseInner
     */
    'officeId'?: string;
    /**
     * The Kenjo Id of the department for this employee.
     * @type {string}
     * @memberof UserAccountsListEmployeesResponseInner
     */
    'departmentId'?: string;
    /**
     * The job title for this employee.
     * @type {string}
     * @memberof UserAccountsListEmployeesResponseInner
     */
    'jobTitle'?: string;
}

